### ISSUE TITLE
Error on swapping maps

### ISSUE THREAD

**Issue by riking** [raiguard/RecipeBook#156] opened 2024-02-04 16:33 UTC
Upon exiting a save soon after joining and loading an older save of the same map, saved with lower mod versions and ignoring mod sync:

```
  84.023 Error AppManagerStates.cpp:1659: The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_configuration_changed
__flib__/dictionary-lite.lua:18: Dictionary module was not properly initialized - ensure that all lifecycle events are handled.
stack traceback:
	[C]: in function 'error'
	__flib__/dictionary-lite.lua:18: in function 'get_data'
	__flib__/dictionary-lite.lua:423: in function 'new'
	__RecipeBook__/scripts/util.lua:246: in function 'new_dictionary'
	__RecipeBook__/scripts/database.lua:39: in function 'build'
	__RecipeBook__/scripts/migrations.lua:16: in function 'func'
	__flib__/migration.lua:66: in function 'run'
	__flib__/migration.lua:93: in function 'on_config_changed'
	__flib__/migration.lua:106: in function <__flib__/migration.lua:105>
```

First save mods: 
![image](https://github.com/raiguard/RecipeBook/assets/627891/6d5722ed-6dde-4f5e-8e3c-cad5b35cde8f)

Second save (downgrade) mods, clicking Load instead of Sync Mods and Load:
![image](https://github.com/raiguard/RecipeBook/assets/627891/f91749ba-3411-41a1-a58e-8ec458f28fe3)

**Comment by raiguard** [comment] 2024-05-05 06:28
Please provide the save file... I have a bug report template for a reason!

**Comment by raiguard** [comment] 2024-05-05 06:33
Nevermind, duplicate of #162.

**Closed by raiguard** 2024-05-05 06:33 UTC
Labels: pending
