### ISSUE TITLE
Error while running event RecipeBook::on_init()

### ISSUE THREAD

**Issue by Mollyarty** [raiguard/RecipeBook#168] opened 2024-07-28 05:28 UTC
posting this here because idk what else to do. I'm more than 200 hours into my save, I can't lose it now.

The mod Recipe Book (3.5.9) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_init()
__RecipeBook__/scripts/database.lua:106: attempt to index field 'item' (a nil value)
stack traceback:
	__RecipeBook__/scripts/database.lua:106: in function 'update_launch_products'
	__RecipeBook__/scripts/database.lua:148: in function 'handle_research_updated'
	__RecipeBook__/scripts/database.lua:99: in function 'check_force'
	__RecipeBook__/scripts/database.lua:89: in function 'new'
	__RecipeBook__/control.lua:182: in function <__RecipeBook__/control.lua:174>

**Comment by raiguard** [comment] 2024-07-28 05:54
Duplicate of #167

**Closed by raiguard** 2024-07-28 05:54 UTC

**Comment by Mollyarty** [comment] 2024-07-28 22:45
But how do I fix it?

**Comment by raiguard** [comment] 2024-07-29 08:13
I already fixed it, see the other issue. Update the `Factorio Library` mod and you'll be good to go.
