### ISSUE TITLE
Non-recoverable error: RecipeBook::rb-open-selected: attempt to concatenate local 'inner' (a nil value)

### ISSUE THREAD

**Issue by nmalaguti** [raiguard/RecipeBook#148] opened 2023-12-03 15:33 UTC
I encountered this server error in a multiplayer game.

```
136510.185 Error MainLoop.cpp:1391: Exception at tick 2159756: The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::rb-open-selected (ID 220)
__RecipeBook__/scripts/formatter.lua:60: attempt to concatenate local 'inner' (a nil value)
stack traceback:
        __RecipeBook__/scripts/formatter.lua:60: in function 'rich_text'
        __RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
        __RecipeBook__/scripts/formatter.lua:566: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/formatter.lua:120: in function '?'
        __RecipeBook__/scripts/formatter.lua:350: in function 'get_tooltip_deets'
        __RecipeBook__/scripts/formatter.lua:582: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/gui/info/list-box.lua:95: in function 'update'
        __RecipeBook__/scripts/gui/info/index.lua:328: in function 'update_contents'
        __RecipeBook__/scripts/gui/info/index.lua:606: in function 'build'
        __RecipeBook__/control.lua:43: in function 'OPEN_PAGE'
        __RecipeBook__/control.lua:459: in function <__RecipeBook__/control.lua:419>
136510.187 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Recipe Book (3.5.7) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::rb-open-selected (ID 220)
__RecipeBook__/scripts/formatter.lua:60: attempt to concatenate local 'inner' (a nil value)
stack traceback:
        __RecipeBook__/scripts/formatter.lua:60: in function 'rich_text'
        __RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
        __RecipeBook__/scripts/formatter.lua:566: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/formatter.lua:120: in function '?'
        __RecipeBook__/scripts/formatter.lua:350: in function 'get_tooltip_deets'
        __RecipeBook__/scripts/formatter.lua:582: in function <__RecipeBook__/scripts/formatter.lua:534>
        (...tail calls...)
        __RecipeBook__/scripts/gui/info/list-box.lua:95: in function 'update'
        __RecipeBook__/scripts/gui/info/index.lua:328: in function 'update_contents'
        __RecipeBook__/scripts/gui/info/index.lua:606: in function 'build'
        __RecipeBook__/control.lua:43: in function 'OPEN_PAGE'
        __RecipeBook__/control.lua:459: in function <__RecipeBook__/control.lua:419>"
136510.188 Info ServerMultiplayerManager.cpp:816: updateTick(2159756) changing state from(InGame) to(Failed)
136510.189 Quitting: multiplayer error.
```

Installed Mods:

```
aai-containers_0.2.11.zip
aai-industry_0.5.22.zip
aai-signal-transmission_0.4.9.zip
aai-vehicles-ironclad_0.6.8.zip
AfraidOfTheDark_1.1.1.zip
alien-biomes_0.6.8.zip
AutoDeconstruct_0.3.12.zip
Automatic_Train_Painter_1.2.0.zip
BottleneckLite_1.2.8.zip
bullet-trails_0.6.2.zip
combat-mechanics-overhaul_0.6.24.zip
CopyPasteModules_0.1.1.zip
equipment-gantry_0.1.5.zip
even-distribution_1.0.10.zip
factoryplanner_1.1.76.zip
FactorySearch_1.10.14.zip
flib_0.13.0.zip
grappling-gun_0.3.3.zip
informatron_0.3.4.zip
jetpack_0.3.14.zip
Milestones_1.3.20.zip
mod-list.json
mod-settings.dat
ModuleInserterSimplified_1.1.4.zip
PickerAtheneum_1.2.5.zip
PickerBeltTools_1.2.6.zip
PickerExtended_4.1.4.zip
qol_research_3.3.3.zip
RateCalculator_3.2.3.zip
RecipeBook_3.5.7.zip
robot_attrition_0.5.15.zip
shield-projector_0.1.6.zip
Shortcuts-ick_1.1.28.zip
simhelper_1.1.5.zip
slightly_smarter_pipette_0.0.11.zip
space-exploration-graphics-2_0.6.1.zip
space-exploration-graphics-3_0.6.2.zip
space-exploration-graphics-4_0.6.3.zip
space-exploration-graphics-5_0.6.1.zip
space-exploration-graphics_0.6.16.zip
space-exploration-menu-simulations_0.6.8.zip
space-exploration-official-modpack_0.6.3.zip
space-exploration-postprocess_0.6.27.zip
space-exploration_0.6.119.zip
Squeak Through_1.8.2.zip
StatsGui_1.4.1.zip
stdlib_1.4.8.zip
textplates_0.6.10.zip
Todo-List_19.3.0.zip
VehicleSnap_1.18.5.zip
WireShortcuts_1.1.13.zip
YARM_0.10.14.zip
```

**Comment by raiguard** [comment] 2023-12-12 21:08
Closing in favor of #149, since it's the same fundamental problem even though the exact traces are different. If you can get a consistent reproduction please send me your save file and the reproduction steps in that issue.

**Closed by raiguard** 2023-12-12 21:08 UTC
