### ISSUE TITLE
[BUG][3.5.5] __RecipeBook__/scripts/formatter.lua:364: attempt to concatenate field '?' (a nil value)

### ISSUE THREAD

**Issue by ZwerOxotnik** [raiguard/RecipeBook#135] opened 2023-07-28 18:41 UTC
### Description

[factorio-current.log](https://github.com/raiguard/RecipeBook/files/12197399/factorio-current.log)

### Reproduction

1. Connect to a server.
2. Save the game while the mod didn't translate everything.
3. Load in SP -> crash right away.

**Comment by ZwerOxotnik** [comment] 2023-07-28 18:44
nvm, everyone got the same error on the server too while I was AFK and the mod translated 95% for me. Only host and I was online.

**Comment by raiguard** [comment] 2023-07-30 23:08
I'm not able to reproduce the crash with the mods in your log file. Please send me a save file with consistent reproduction steps.

**Comment by ZwerOxotnik** [comment] 2023-07-31 06:46
Unfortunately, Factorio doesn't sync versions of mods for saves properly. It triggers another event which resets some data and doesn't cause the issue again, so I don't know how to provide stuff properly.

**Comment by raiguard** [comment] 2023-08-01 20:39
In that case, I'll go ahead and close this. Both issues are almost guaranteed to be related to the on_load info caching, and is the primary reason why I am rewriting the mod from scratch. This shouldn't be an issue in 4.0.

**Closed by raiguard** 2023-08-01 20:39 UTC
